language: node_js
node_js:
  - "8"
install: npm i -g data-cli
script:
  - git fetch origin npm:npm
  - git checkout npm
  - git remote rm origin
  - git remote add origin $REMOTE_GIT
after_script:
  - npm version patch
  - git push origin npm
  - data push
branches:
  only:
  - master
  - npm
